package org.osre;

import org.osre.*;

public class AssetLink {
     
    String[] assets = {
	"[ASSETS, ATC-13, BUILDINGS, Wood Frame (Low Rise)]",     
	"[ASSETS, ATC-13, BUILDINGS, Light Metal (Low Rise)]",
	"[ASSETS, ATC-13, BUILDINGS, Unreinforced Masonry, Bearing Wall, Low Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Unreinforced Masonry, Bearing Wall, Medium Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Unreinforced Masonry, with Load Bearing Frame, Low Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Unreinforced Masonry, with Load Bearing Frame, Medium Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Unreinforced Masonry, with Load Bearing Frame, High Rise]",
	"[ASSETS, ATC-13, BUILDINGS, RC Shear Wall, with Moment-Resisting Frame, Low Rise]",
	"[ASSETS, ATC-13, BUILDINGS, RC Shear Wall, with Moment-Resisting Frame, Medium Rise]",
	"[ASSETS, ATC-13, BUILDINGS, RC Shear Wall, with Moment-Resisting Frame, High Rise]",
	"[ASSETS, ATC-13, BUILDINGS, RC Shear Wall, without Moment-Resisting Frame, Low Rise]",
	"[ASSETS, ATC-13, BUILDINGS, RC Shear Wall, without Moment-Resisting Frame, Medium Rise]",
	"[ASSETS, ATC-13, BUILDINGS, RC Shear Wall, without Moment-Resisting Frame, High Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Reinforced Masonry Shear Wall, with Moment-Resisting Frame, Low Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Reinforced Masonry Shear Wall, with Moment-Resisting Frame, Medium Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Reinforced Masonry Shear Wall, with Moment-Resisting Frame, High Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Reinforced Masonry Shear Wall, without Moment-Resisting Frame, Low Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Reinforced Masonry Shear Wall, without Moment-Resisting Frame, Medium Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Reinforced Masonry Shear Wall, without Moment-Resisting Frame, High Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Braced Steel Frames, Low Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Braced Steel Frames, Medium Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Braced Steel Frames, High Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Moment-Resisting Steel Frame, Perimeter Frame, Steel, Low Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Moment-Resisting Steel Frame, Perimeter Frame, Steel, Medium Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Moment-Resisting Steel Frame, Perimeter Frame, Steel, High Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Moment-Resisting Steel Frame, Distributed Frame, Steel, Low Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Moment-Resisting Steel Frame, Distributed Frame, Steel, Medium Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Moment-Resisting Steel Frame, Distributed Frame, Steel, High Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Moment-Resisting Steel Frame, Distributed Frame, Ductile Concrete, Low Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Moment-Resisting Steel Frame, Distributed Frame, Ductile Concrete, Medium Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Moment-Resisting Steel Frame, Distributed Frame, Ductile Concrete, High Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Moment-Resisting Steel Frame, Distributed Frame, Non-Ductile Concrete, Low Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Moment-Resisting Steel Frame, Distributed Frame, Non-Ductile Concrete, Medium Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Moment-Resisting Steel Frame, Distributed Frame, Non-Ductile Concrete, High Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Precast Concrete, Low Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Precast Concrete, Medium Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Precast Concrete, High Rise]",
	"[ASSETS, ATC-13, BUILDINGS, Long-Span (Low Rise)]",
	"[ASSETS, ATC-13, BUILDINGS, Tilt-Up (Low Rise)]",
	"[ASSETS, ATC-13, BUILDINGS, Mobile Homes]",
	"[ASSETS, ATC-13, BRIDGES, Conventional, Multiple Simple Span]",
	"[ASSETS, ATC-13, BRIDGES, Conventional, Continous/Monolithic]",
	"[ASSETS, ATC-13, BRIDGES, Major]",
	"[ASSETS, ATC-13, PIPELINES, Underground]",
	"[ASSETS, ATC-13, PIPELINES, At Grade]",
	"[ASSETS, ATC-13, DAMS, Concrete]",
	"[ASSETS, ATC-13, DAMS, Earth and rock fill]",
	"[ASSETS, ATC-13, TUNNELS, Alluvium]",
	"[ASSETS, ATC-13, TUNNELS, Rock]",
	"[ASSETS, ATC-13, TUNNELS, Cut and Cover]",
	"[ASSETS, ATC-13, STORAGE TANK, Underground, Liquid]",
	"[ASSETS, ATC-13, STORAGE TANK, Underground, Solid]",
	"[ASSETS, ATC-13, STORAGE TANK, On Ground, Liquid]",
	"[ASSETS, ATC-13, STORAGE TANK, On Ground, Solid]",
	"[ASSETS, ATC-13, STORAGE TANK, Elevated, Liquid]",
	"[ASSETS, ATC-13, STORAGE TANK, Elevated, Solid]",
	"[ASSETS, ATC-13, ROADWAYS and PAVEMENTS, Railroad]",
	"[ASSETS, ATC-13, ROADWAYS and PAVEMENTS, Highways]",
	"[ASSETS, ATC-13, ROADWAYS and PAVEMENTS, Runways]",
	"[ASSETS, ATC-13, CHIMNEY, Masonry]",
	"[ASSETS, ATC-13, CHIMNEY, Concrete]",
	"[ASSETS, ATC-13, CHIMNEY, Steel]",
	"[ASSETS, ATC-13, CRANES]",
	"[ASSETS, ATC-13, CONVEYOR SYSTEMS]",
	"[ASSETS, ATC-13, TOWERS, Electrical Transmisson Line, Conventional (less than 100' high)]",
        "[ASSETS, ATC-13, TOWERS, Electrical Transmisson Line, Major (more than 100' high)]",
	"[ASSETS, ATC-13, TOWERS, Broadcast]",
	"[ASSETS, ATC-13, TOWERS, Observation]",
	"[ASSETS, ATC-13, TOWERS, Offshore]",
	"[ASSETS, ATC-13, OTHER STRUCTURES, Canals]",
	"[ASSETS, ATC-13, OTHER STRUCTURES, Earth Retaining Structures (over 20' high)]",
        "[ASSETS, ATC-13, OTHER STRUCTURES, Waterfront Structure]",
        "[ASSETS, ATC-13, EQUIPMENTS, Residential]",
        "[ASSETS, ATC-13, EQUIPMENTS, Office (Furnuture, Computers, etc.)]",
        "[ASSETS, ATC-13, EQUIPMENTS, Electrical]",
        "[ASSETS, ATC-13, EQUIPMENTS, Mechanical]",
        "[ASSETS, ATC-13, EQUIPMENTS, High Technology & Laboratory]",
        "[ASSETS, ATC-13, EQUIPMENTS, Trains, Trucks, Airplanes & other vehicles]",
        "[ASSETS, JAPANESE, BUILDINGS, Wood Frame, Constructed on -1950]",
        "[ASSETS, JAPANESE, BUILDINGS, Wood Frame, Constructed on 1951-1960]",
        "[ASSETS, JAPANESE, BUILDINGS, Wood Frame, Constructed on 1961-1970]",
        "[ASSETS, JAPANESE, BUILDINGS, Wood Frame, Constructed on 1971-1980]",
        "[ASSETS, JAPANESE, BUILDINGS, Wood Frame, Constructed on 1981-]",
        "[ASSETS, JAPANESE, BUILDINGS, Wood Frame, All]",
        "[ASSETS, JAPANESE, BUILDINGS, Reinforced Concrete, Constructed on -1971]",
        "[ASSETS, JAPANESE, BUILDINGS, Reinforced Concrete, Constructed on 1972-1981]",
        "[ASSETS, JAPANESE, BUILDINGS, Reinforced Concrete, Constructed on 1982-]",
        "[ASSETS, JAPANESE, BUILDINGS, Reinforced Concrete, All]",
        "[ASSETS, JAPANESE, BUILDINGS, Steel Frame, Constructed on -1981]",
        "[ASSETS, JAPANESE, BUILDINGS, Steel Frame, Constructed on 1982-]",
        "[ASSETS, JAPANESE, BUILDINGS, Steel Frame, All]",
        "[ASSETS, JAPANESE, BUILDINGS, Light Steel Frame, All]"};

}
